spring:
  liquibase:
    change-log: classpath:database/liquibase-changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/comic_libraries
    password: afergon
    username: afergon